# Generated by Django 4.0.4 on 2024-01-25 10:45
import logging

from django.db import migrations


def create_brightid_connection(apps, schema_editor):
    bright_id_connection_cls = apps.get_model("authentication", "BrightIDConnection")
    user_profile_cls = apps.get_model('authentication', 'UserProfile')

    for user_profile in user_profile_cls.objects.exclude(initial_context_id__isnull=True, initial_context_id=''):
        try:
            bright_id_connection_cls.objects.get(user_profile=user_profile)
        except bright_id_connection_cls.DoesNotExist:
            bright_id_connection_cls(user_profile=user_profile, context_id=user_profile.initial_context_id).save()
        except Exception as e:
            logging.error(f'error while trying to create brightidconnection for user {user_profile.pk}: {e}')


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0029_remove_wallet_unique_wallet_address_and_more'),
    ]

    operations = [
        migrations.RunPython(create_brightid_connection)
    ]
